<?php

return [
    'categories' => [
        'core' => 'پایه',
        'sales' => 'فروش',
        'operations' => 'عملیات',
        'analytics' => 'گزارش و تحلیل',
        'communication' => 'ارتباطات',
        'finance' => 'مالی',
        'support' => 'پشتیبانی',
        'automation' => 'اتوماسیون',
        'integration' => 'یکپارچگی',
    ],

    'slug_migrations' => [
        'sms' => 'mod-sms',
        'advanced_reports' => 'mod-reports',
        'automation' => 'mod-automation',
    ],

    'modules' => [
        [
            'name' => 'پایه CRM',
            'slug' => 'core-base',
            'description' => 'فعال‌سازی مجموعه، داشبورد، مخاطبین، لید، معاملات پایه، تسک و کاربران — قیمت بر اساس تعداد کارمند',
            'category' => 'core',
            'sort_order' => 0,
            'icon' => 'tabler-building-store',
            'nav_route' => null,
            'is_core' => true,
            'features' => [
                'داشبورد مجموعه',
                'مخاطبین و شرکت‌ها',
                'لید، کمپین و قیف بازاریابی',
                'معاملات و کاریز فروش',
                'گفتگوی تیم اعضا',
                'تسک‌ها و فعالیت‌های پایه',
                'گزارش فروش و بازاریابی',
                'مدیریت کاربران تا سقف صندلی',
            ],
            'price' => 832200,
            'monthly_price' => 832200,
            'semi_annual_price' => 4161000,
            'annual_price' => 7489800,
            'seat_monthly_price' => 832200,
            'seat_semi_annual_price' => 4161000,
            'seat_annual_price' => 7489800,
        ],
        [
            'name' => 'کاریز فروش پیشرفته',
            'slug' => 'mod-sales-funnel',
            'description' => 'کاریز فروش پیشرفته، فیلتر، پیش‌بینی فروش و دلایل شکست معامله',
            'category' => 'sales',
            'sort_order' => 10,
            'icon' => 'tabler-chart-funnel',
            'nav_route' => 'apps-crm-deals',
            'is_core' => false,
            'features' => ['چند کاریز اختصاصی', 'فیلتر پیشرفته', 'پیش‌بینی فروش', 'دلایل شکست'],
            'price' => 590000,
            'monthly_price' => 590000,
            'semi_annual_price' => 2950000,
            'annual_price' => 5310000,
        ],
        [
            'name' => 'پروژه و کارت',
            'slug' => 'mod-projects',
            'description' => 'مدیریت پروژه‌ها و فرآیندهای جاری با کارت Kanban',
            'category' => 'operations',
            'sort_order' => 20,
            'icon' => 'tabler-layout-kanban',
            'nav_route' => 'apps-crm-projects',
            'is_core' => false,
            'features' => ['کارت Kanban', 'فرآیندهای سفارشی', 'تخصیص چندکاربره', 'برچسب‌گذاری'],
            'price' => 690000,
            'monthly_price' => 690000,
            'semi_annual_price' => 3450000,
            'annual_price' => 6210000,
        ],
        [
            'name' => 'گزارش و هدف‌گذاری',
            'slug' => 'mod-reports',
            'description' => 'گزارش‌های تحلیلی، هدف‌گذاری تیم و کاربر، خروجی Excel',
            'category' => 'analytics',
            'sort_order' => 30,
            'icon' => 'tabler-report-analytics',
            'nav_route' => 'apps-crm-reports',
            'is_core' => false,
            'features' => ['گزارش فروش', 'نرخ تبدیل', 'هدف‌گذاری', 'خروجی Excel'],
            'price' => 490000,
            'monthly_price' => 490000,
            'semi_annual_price' => 2450000,
            'annual_price' => 4410000,
        ],
        [
            'name' => 'پنل پیامک',
            'slug' => 'mod-sms',
            'description' => 'ارسال پیامک تکی و گروهی به مشتریان و لیدها',
            'category' => 'communication',
            'sort_order' => 40,
            'icon' => 'tabler-message',
            'nav_route' => 'apps-crm-sms',
            'is_core' => false,
            'features' => ['ارسال گروهی', 'قالب پیام', 'زمان‌بندی ارسال', 'تاریخچه'],
            'price' => 490000,
            'monthly_price' => 490000,
            'semi_annual_price' => 2450000,
            'annual_price' => 4410000,
        ],
        [
            'name' => 'وب‌فرم',
            'slug' => 'mod-web-forms',
            'description' => 'ایجاد فرم لید، معامله و کارت با لینک و QR',
            'category' => 'communication',
            'sort_order' => 50,
            'icon' => 'tabler-forms',
            'nav_route' => 'apps-crm-web-forms',
            'is_core' => false,
            'features' => ['فرم سفارشی', 'ایجاد خودکار لید', 'اشتراک لینک/QR', 'iframe'],
            'price' => 390000,
            'monthly_price' => 390000,
            'semi_annual_price' => 1950000,
            'annual_price' => 3510000,
        ],
        [
            'name' => 'کاتالوگ محصول',
            'slug' => 'mod-products',
            'description' => 'مدیریت محصولات دستی و نمایش در لید و قیف فروش',
            'category' => 'sales',
            'sort_order' => 55,
            'icon' => 'tabler-package',
            'nav_route' => 'apps-crm-products',
            'is_core' => false,
            'features' => ['ثبت دستی محصول', 'دسته‌بندی', 'SKU و موجودی', 'اتصال به لید و معامله'],
            'price' => 490000,
            'monthly_price' => 490000,
            'semi_annual_price' => 2450000,
            'annual_price' => 4410000,
        ],
        [
            'name' => 'فاکتور و پرداخت',
            'slug' => 'mod-invoicing',
            'description' => 'صدور پیش‌فاکتور، فاکتور، صورتحساب و اتصال درگاه',
            'category' => 'finance',
            'sort_order' => 60,
            'icon' => 'tabler-file-invoice',
            'nav_route' => 'apps-crm-invoicing',
            'is_core' => false,
            'features' => ['پیش‌فاکتور', 'فاکتور', 'صورتحساب', 'درگاه پرداخت'],
            'price' => 590000,
            'monthly_price' => 590000,
            'semi_annual_price' => 2950000,
            'annual_price' => 5310000,
        ],
        [
            'name' => 'تیکتینگ',
            'slug' => 'mod-ticketing',
            'description' => 'سامانه تیکت و پرتال مشتریان',
            'category' => 'support',
            'sort_order' => 70,
            'icon' => 'tabler-ticket',
            'nav_route' => 'apps-crm-ticketing',
            'is_core' => false,
            'features' => ['ثبت تیکت', 'پرتال مشتری', 'اولویت‌بندی', 'پیگیری وضعیت'],
            'price' => 790000,
            'monthly_price' => 790000,
            'semi_annual_price' => 3950000,
            'annual_price' => 7110000,
        ],
        [
            'name' => 'اتوماسیون',
            'slug' => 'mod-automation',
            'description' => 'گردش‌کار خودکار: رویداد، شرط، اقدام — تخصیص، یادآور و تسک بدون افزونه اضافه',
            'category' => 'automation',
            'sort_order' => 80,
            'icon' => 'tabler-robot',
            'nav_route' => 'apps-crm-automation',
            'is_core' => false,
            'features' => ['قوانین خودکار', 'یادآور هوشمند', 'تخصیص خودکار', 'پیامک خودکار'],
            'requires_modules' => [
                ['slug' => 'core-base', 'label' => 'پایه CRM', 'reason' => 'برای دسترسی به لیدها و معاملات'],
            ],
            'optional_modules' => [
                ['slug' => 'mod-sms', 'label' => 'پنل پیامک', 'reason' => 'برای اقدام «ارسال پیامک خودکار» در قوانین'],
            ],
            'price' => 890000,
            'monthly_price' => 890000,
            'semi_annual_price' => 4450000,
            'annual_price' => 8010000,
        ],
        [
            'name' => 'یکپارچگی',
            'slug' => 'mod-integrations',
            'description' => 'API، وب‌هوک، VoIP و اتصال به سایت',
            'category' => 'integration',
            'sort_order' => 90,
            'icon' => 'tabler-plug-connected',
            'nav_route' => 'apps-crm-integrations',
            'is_core' => false,
            'features' => ['REST API', 'Webhook', 'VoIP/Caller ID', 'اتصال وردپرس'],
            'price' => 690000,
            'monthly_price' => 690000,
            'semi_annual_price' => 3450000,
            'annual_price' => 6210000,
        ],
        [
            'name' => 'هوش تجاری BI',
            'slug' => 'mod-bi',
            'description' => 'گزارش‌ساز BI و داشبورد هوش تجاری',
            'category' => 'analytics',
            'sort_order' => 100,
            'icon' => 'tabler-chart-dots-3',
            'nav_route' => 'apps-crm-bi',
            'is_core' => false,
            'features' => ['گزارش‌ساز', 'داشبورد BI', 'اتصال Looker Studio', 'تحلیل پیشرفته'],
            'price' => 990000,
            'monthly_price' => 990000,
            'semi_annual_price' => 4950000,
            'annual_price' => 8910000,
        ],
    ],
];
