<?php

use App\Domain\Shared\Enums\RoleName;

$all = [
    'contacts.read',
    'contacts.create',
    'contacts.update',
    'contacts.delete',
    'deals.read',
    'deals.create',
    'deals.update',
    'deals.delete',
    'deals.view_unassigned',
    'reports.sales.read',
    'bi.read',
    'leads.read',
    'leads.create',
    'leads.update',
    'leads.delete',
    'leads.view_unassigned',
    'leads.assign',
    'campaigns.read',
    'campaigns.create',
    'campaigns.update',
    'campaigns.delete',
    'marketing_funnel.read',
    'marketing_funnel.update',
    'web_forms.read',
    'web_forms.create',
    'web_forms.manage',
    'sms.read',
    'sms.send',
    'sms.manage',
    'sms.credit',
    'automation.read',
    'automation.manage',
    'invoicing.read',
    'invoicing.create',
    'invoicing.update',
    'finance_handoffs.read',
    'finance_handoffs.manage',
    'tasks.read',
    'tasks.create',
    'tasks.update',
    'tasks.delete',
    'tasks.assign',
    'tasks.view_team',
    'daily_reports.read',
    'daily_reports.create',
    'daily_reports.submit',
    'daily_reports.review',
    'daily_reports.view_team',
    'activities.read',
    'activities.create',
    'activities.update',
    'activities.delete',
    'team_chat.read',
    'users.manage',
    'invitations.manage',
    'tenant.settings',
    'broadcasts.send',
    'products.read',
    'products.create',
    'products.update',
    'products.delete',
    'integrations.manage',
];

$sales = [
    'contacts.read', 'contacts.create', 'contacts.update', 'contacts.delete',
    'deals.read', 'deals.create', 'deals.update', 'deals.delete',
    'deals.view_unassigned',
    'leads.read', 'leads.view_unassigned', 'leads.assign',
    'marketing_funnel.read',
    'reports.sales.read',
    'bi.read',
    'sms.read', 'sms.send',
    'products.read',
    'products.create',
    'products.update',
];

$marketing = [
    'leads.read', 'leads.create', 'leads.update', 'leads.delete',
    'leads.view_unassigned',
    'campaigns.read', 'campaigns.create', 'campaigns.update', 'campaigns.delete',
    'marketing_funnel.read', 'marketing_funnel.update',
    'bi.read',
    'web_forms.read', 'web_forms.create', 'web_forms.manage', 'sms.read', 'sms.send', 'sms.manage', 'sms.credit', 'automation.read', 'automation.manage',
    'products.read',
];

$finance = [
    'invoicing.read', 'invoicing.create', 'invoicing.update',
    'finance_handoffs.read', 'finance_handoffs.manage',
    'bi.read',
    'products.read',
];

$shared = [
    'tasks.read', 'tasks.create', 'tasks.update', 'tasks.delete',
    'daily_reports.read', 'daily_reports.create', 'daily_reports.submit',
    'activities.read', 'activities.create', 'activities.update', 'activities.delete',
    'team_chat.read',
];

$management = [
    'users.manage', 'invitations.manage', 'broadcasts.send',
    'daily_reports.review', 'daily_reports.view_team',
    'tasks.assign', 'tasks.view_team',
    'leads.assign',
];

return [
    'catalog' => [
        'contacts.read' => ['label' => 'مشاهده مخاطبین', 'group' => 'sales', 'casl' => ['action' => 'read', 'subject' => 'Contacts']],
        'contacts.create' => ['label' => 'ایجاد مخاطب', 'group' => 'sales', 'casl' => ['action' => 'create', 'subject' => 'Contacts']],
        'contacts.update' => ['label' => 'ویرایش مخاطب', 'group' => 'sales', 'casl' => ['action' => 'update', 'subject' => 'Contacts']],
        'contacts.delete' => ['label' => 'حذف مخاطب', 'group' => 'sales', 'casl' => ['action' => 'delete', 'subject' => 'Contacts']],
        'deals.read' => ['label' => 'مشاهده معاملات', 'group' => 'sales', 'casl' => ['action' => 'read', 'subject' => 'Deals']],
        'deals.create' => ['label' => 'ایجاد معامله', 'group' => 'sales', 'casl' => ['action' => 'create', 'subject' => 'Deals']],
        'deals.update' => ['label' => 'ویرایش معامله', 'group' => 'sales', 'casl' => ['action' => 'update', 'subject' => 'Deals']],
        'deals.delete' => ['label' => 'حذف معامله', 'group' => 'sales', 'casl' => ['action' => 'delete', 'subject' => 'Deals']],
        'deals.view_unassigned' => ['label' => 'مشاهده معاملات بدون مسئول', 'group' => 'sales', 'casl' => ['action' => 'read', 'subject' => 'UnassignedDeals']],
        'reports.sales.read' => ['label' => 'گزارش فروش', 'group' => 'sales', 'casl' => ['action' => 'read', 'subject' => 'Reports']],
        'bi.read' => ['label' => 'هوش تجاری BI', 'group' => 'sales', 'casl' => ['action' => 'read', 'subject' => 'BI']],
        'leads.read' => ['label' => 'مشاهده لیدها', 'group' => 'marketing', 'casl' => ['action' => 'read', 'subject' => 'Leads']],
        'leads.create' => ['label' => 'ایجاد لید', 'group' => 'marketing', 'casl' => ['action' => 'create', 'subject' => 'Leads']],
        'leads.update' => ['label' => 'ویرایش لید', 'group' => 'marketing', 'casl' => ['action' => 'update', 'subject' => 'Leads']],
        'leads.delete' => ['label' => 'حذف لید', 'group' => 'marketing', 'casl' => ['action' => 'delete', 'subject' => 'Leads']],
        'leads.view_unassigned' => ['label' => 'مشاهده لیدهای بدون مسئول', 'group' => 'marketing', 'casl' => ['action' => 'read', 'subject' => 'UnassignedLeads']],
        'leads.assign' => ['label' => 'ارجاع و واگذاری لید', 'group' => 'management', 'casl' => ['action' => 'assign', 'subject' => 'Leads']],
        'campaigns.read' => ['label' => 'مشاهده کمپین‌ها', 'group' => 'marketing', 'casl' => ['action' => 'read', 'subject' => 'Campaigns']],
        'campaigns.create' => ['label' => 'ایجاد کمپین', 'group' => 'marketing', 'casl' => ['action' => 'create', 'subject' => 'Campaigns']],
        'campaigns.update' => ['label' => 'ویرایش کمپین', 'group' => 'marketing', 'casl' => ['action' => 'update', 'subject' => 'Campaigns']],
        'campaigns.delete' => ['label' => 'حذف کمپین', 'group' => 'marketing', 'casl' => ['action' => 'delete', 'subject' => 'Campaigns']],
        'marketing_funnel.read' => ['label' => 'قیف بازاریابی', 'group' => 'marketing', 'casl' => ['action' => 'read', 'subject' => 'MarketingFunnel']],
        'marketing_funnel.update' => ['label' => 'ویرایش قیف بازاریابی', 'group' => 'marketing', 'casl' => ['action' => 'update', 'subject' => 'MarketingFunnel']],
        'web_forms.read' => ['label' => 'وب‌فرم', 'group' => 'marketing', 'casl' => ['action' => 'read', 'subject' => 'WebForms']],
        'web_forms.create' => ['label' => 'ایجاد وب‌فرم', 'group' => 'marketing', 'casl' => ['action' => 'create', 'subject' => 'WebForms']],
        'web_forms.manage' => ['label' => 'مدیریت وب‌فرم', 'group' => 'marketing', 'casl' => ['action' => 'manage', 'subject' => 'WebForms']],
        'sms.read' => ['label' => 'مشاهده پنل پیامک', 'group' => 'marketing', 'casl' => ['action' => 'read', 'subject' => 'Sms']],
        'sms.send' => ['label' => 'ارسال پیامک', 'group' => 'marketing', 'casl' => ['action' => 'create', 'subject' => 'Sms']],
        'sms.manage' => ['label' => 'مدیریت قالب پیامک', 'group' => 'marketing', 'casl' => ['action' => 'update', 'subject' => 'Sms']],
        'sms.credit' => ['label' => 'خرید شارژ پیامک', 'group' => 'management', 'casl' => ['action' => 'manage', 'subject' => 'SmsCredit']],
        'automation.read' => ['label' => 'مشاهده اتوماسیون', 'group' => 'marketing', 'casl' => ['action' => 'read', 'subject' => 'Automation']],
        'automation.manage' => ['label' => 'مدیریت قوانین اتوماسیون', 'group' => 'marketing', 'casl' => ['action' => 'manage', 'subject' => 'Automation']],
        'invoicing.read' => ['label' => 'مشاهده فاکتور', 'group' => 'finance', 'casl' => ['action' => 'read', 'subject' => 'Invoicing']],
        'invoicing.create' => ['label' => 'ایجاد فاکتور', 'group' => 'finance', 'casl' => ['action' => 'create', 'subject' => 'Invoicing']],
        'invoicing.update' => ['label' => 'ویرایش فاکتور', 'group' => 'finance', 'casl' => ['action' => 'update', 'subject' => 'Invoicing']],
        'finance_handoffs.read' => ['label' => 'مشاهده ارجاع مالی', 'group' => 'finance', 'casl' => ['action' => 'read', 'subject' => 'FinanceHandoffs']],
        'finance_handoffs.manage' => ['label' => 'مدیریت ارجاع مالی', 'group' => 'finance', 'casl' => ['action' => 'manage', 'subject' => 'FinanceHandoffs']],
        'tasks.read' => ['label' => 'مشاهده تسک', 'group' => 'shared', 'casl' => ['action' => 'read', 'subject' => 'Tasks']],
        'tasks.create' => ['label' => 'ایجاد تسک', 'group' => 'shared', 'casl' => ['action' => 'create', 'subject' => 'Tasks']],
        'tasks.update' => ['label' => 'ویرایش تسک', 'group' => 'shared', 'casl' => ['action' => 'update', 'subject' => 'Tasks']],
        'tasks.delete' => ['label' => 'حذف تسک', 'group' => 'shared', 'casl' => ['action' => 'delete', 'subject' => 'Tasks']],
        'tasks.assign' => ['label' => 'واگذاری تسک به دیگران', 'group' => 'management', 'casl' => ['action' => 'assign', 'subject' => 'Tasks']],
        'tasks.view_team' => ['label' => 'مشاهده تسک‌های اعضای تیم', 'group' => 'management', 'casl' => ['action' => 'read', 'subject' => 'TeamTasks']],
        'daily_reports.read' => ['label' => 'مشاهده گزارش کار روزانه', 'group' => 'shared', 'casl' => ['action' => 'read', 'subject' => 'DailyReports']],
        'daily_reports.create' => ['label' => 'ثبت گزارش کار روزانه', 'group' => 'shared', 'casl' => ['action' => 'create', 'subject' => 'DailyReports']],
        'daily_reports.submit' => ['label' => 'ارسال گزارش به مدیر', 'group' => 'shared', 'casl' => ['action' => 'update', 'subject' => 'DailyReports']],
        'daily_reports.review' => ['label' => 'بازبینی و امتیازدهی گزارش کار', 'group' => 'management', 'casl' => ['action' => 'manage', 'subject' => 'DailyReports']],
        'daily_reports.view_team' => ['label' => 'مشاهده گزارش‌های اعضای تیم', 'group' => 'management', 'casl' => ['action' => 'read', 'subject' => 'TeamDailyReports']],
        'activities.read' => ['label' => 'مشاهده فعالیت', 'group' => 'shared', 'casl' => ['action' => 'read', 'subject' => 'Activities']],
        'activities.update' => ['label' => 'ویرایش فعالیت', 'group' => 'shared', 'casl' => ['action' => 'update', 'subject' => 'Activities']],
        'activities.create' => ['label' => 'ثبت فعالیت', 'group' => 'shared', 'casl' => ['action' => 'create', 'subject' => 'Activities']],
        'activities.delete' => ['label' => 'حذف فعالیت', 'group' => 'shared', 'casl' => ['action' => 'delete', 'subject' => 'Activities']],
        'team_chat.read' => ['label' => 'گفتگوی تیم', 'group' => 'shared', 'casl' => ['action' => 'read', 'subject' => 'TeamChat']],
        'users.manage' => ['label' => 'مدیریت کاربران', 'group' => 'management', 'casl' => ['action' => 'manage', 'subject' => 'Users']],
        'invitations.manage' => ['label' => 'مدیریت دعوت‌ها', 'group' => 'management', 'casl' => ['action' => 'manage', 'subject' => 'Invitations']],
        'tenant.settings' => ['label' => 'تنظیمات مجموعه', 'group' => 'management', 'casl' => ['action' => 'manage', 'subject' => 'TenantSettings']],
        'broadcasts.send' => ['label' => 'پیام به تیم', 'group' => 'management', 'casl' => ['action' => 'manage', 'subject' => 'Broadcasts']],
        'products.read' => ['label' => 'مشاهده محصولات', 'group' => 'sales', 'casl' => ['action' => 'read', 'subject' => 'Products']],
        'products.create' => ['label' => 'ایجاد محصول', 'group' => 'sales', 'casl' => ['action' => 'create', 'subject' => 'Products']],
        'products.update' => ['label' => 'ویرایش محصول', 'group' => 'sales', 'casl' => ['action' => 'update', 'subject' => 'Products']],
        'products.delete' => ['label' => 'حذف محصول', 'group' => 'sales', 'casl' => ['action' => 'delete', 'subject' => 'Products']],
        'integrations.manage' => ['label' => 'مدیریت یکپارچگی', 'group' => 'management', 'casl' => ['action' => 'manage', 'subject' => 'Integrations']],
    ],

    'group_labels' => [
        'sales' => 'فروش',
        'marketing' => 'بازاریابی',
        'finance' => 'مالی',
        'shared' => 'مشترک',
        'management' => 'مدیریت',
    ],

    'role_defaults' => [
        RoleName::Owner->value => $all,
        RoleName::SalesManager->value => array_merge($sales, $shared, $management),
        RoleName::MarketingManager->value => array_merge($marketing, $shared, $management),
        RoleName::FinanceManager->value => array_merge($finance, $shared, $management),
        RoleName::SalesEmployee->value => array_merge(
            ['contacts.read', 'contacts.create', 'contacts.update', 'deals.read', 'deals.create', 'deals.update', 'products.read'],
            ['tasks.read', 'tasks.create', 'tasks.update', 'daily_reports.read', 'daily_reports.create', 'daily_reports.submit', 'activities.read', 'activities.create', 'activities.update', 'team_chat.read'],
        ),
        RoleName::MarketingEmployee->value => array_merge(
            ['leads.read', 'leads.create', 'leads.update', 'campaigns.read', 'marketing_funnel.read', 'products.read'],
            ['tasks.read', 'tasks.create', 'tasks.update', 'daily_reports.read', 'daily_reports.create', 'daily_reports.submit', 'activities.read', 'activities.create', 'activities.update', 'team_chat.read'],
        ),
        RoleName::FinanceEmployee->value => array_merge(
            ['invoicing.read', 'finance_handoffs.read'],
            ['tasks.read', 'tasks.create', 'tasks.update', 'daily_reports.read', 'daily_reports.create', 'daily_reports.submit', 'activities.read', 'activities.create', 'activities.update', 'team_chat.read'],
        ),
    ],
];
