export const staticPrimaryColor = '#4A0E17'
export const staticPrimaryDarkenColor = '#350A10'
export const staticDarkPrimaryColor = '#C75C6D'
export const staticDarkPrimaryDarkenColor = '#A83E50'
export const staticAccentColor = '#D4AF37'
export const staticAccentDarkenColor = '#B99425'
export const themes = {
  light: {
    dark: false,
    colors: {
      'primary': staticPrimaryColor,
      'on-primary': '#fff',
      'primary-darken-1': staticPrimaryDarkenColor,
      'secondary': staticAccentColor,
      'on-secondary': '#211A05',
      'secondary-darken-1': staticAccentDarkenColor,
      'accent': staticAccentColor,
      'on-accent': '#211A05',
      'accent-darken-1': staticAccentDarkenColor,
      'success': '#28C76F',
      'on-success': '#fff',
      'success-darken-1': '#24B364',
      'info': '#00BAD1',
      'on-info': '#fff',
      'info-darken-1': '#00A7BC',
      'warning': '#FF9F43',
      'on-warning': '#fff',
      'warning-darken-1': '#E68F3C',
      'error': '#FF4C51',
      'on-error': '#fff',
      'error-darken-1': '#E64449',
      'background': '#FAF8F4',
      'on-background': '#2D171B',
      'surface': '#fff',
      'on-surface': '#2D171B',
      'grey-50': '#FAFAFA',
      'grey-100': '#F5F0EA',
      'grey-200': '#E9DED2',
      'grey-300': '#D8C6B9',
      'grey-400': '#BCA89C',
      'grey-500': '#9D877D',
      'grey-600': '#7C6861',
      'grey-700': '#604D48',
      'grey-800': '#3F2F31',
      'grey-900': '#241719',
      'grey-light': '#F8F3ED',
      'perfect-scrollbar-thumb': '#D8C6B9',
      'skin-bordered-background': '#fff',
      'skin-bordered-surface': '#fff',
      'expansion-panel-text-custom-bg': '#FBF7EF',
    },
    variables: {
      'code-color': '#A83E50',
      'overlay-scrim-background': '#2D171B',
      'tooltip-background': '#2D171B',
      'overlay-scrim-opacity': 0.5,
      'hover-opacity': 0.06,
      'focus-opacity': 0.1,
      'selected-opacity': 0.08,
      'activated-opacity': 0.16,
      'pressed-opacity': 0.14,
      'dragged-opacity': 0.1,
      'disabled-opacity': 0.4,
      'border-color': '#2D171B',
      'border-opacity': 0.12,
      'table-header-color': '#F0E7DC',
      'high-emphasis-opacity': 0.9,
      'medium-emphasis-opacity': 0.7,
      'switch-opacity': 0.2,
      'switch-disabled-track-opacity': 0.3,
      'switch-disabled-thumb-opacity': 0.4,
      'switch-checked-disabled-opacity': 0.3,
      'track-bg': '#F2EAE2',

      // Shadows
      'shadow-key-umbra-color': '#2D171B',
      'shadow-xs-opacity': 0.10,
      'shadow-sm-opacity': 0.12,
      'shadow-md-opacity': 0.14,
      'shadow-lg-opacity': 0.16,
      'shadow-xl-opacity': 0.18,
    },
  },
  dark: {
    dark: true,
    colors: {
      'primary': staticDarkPrimaryColor,
      'on-primary': '#fff',
      'primary-darken-1': staticDarkPrimaryDarkenColor,
      'secondary': '#E2C15A',
      'on-secondary': '#1F1604',
      'secondary-darken-1': '#C9A332',
      'accent': '#E2C15A',
      'on-accent': '#1F1604',
      'accent-darken-1': '#C9A332',
      'success': '#28C76F',
      'on-success': '#fff',
      'success-darken-1': '#24B364',
      'info': '#00BAD1',
      'on-info': '#fff',
      'info-darken-1': '#00A7BC',
      'warning': '#FF9F43',
      'on-warning': '#fff',
      'warning-darken-1': '#E68F3C',
      'error': '#FF4C51',
      'on-error': '#fff',
      'error-darken-1': '#E64449',
      'background': '#14090D',
      'on-background': '#F6E9EC',
      'surface': '#1E1015',
      'on-surface': '#F6E9EC',
      'grey-50': '#1A0D12',
      'grey-100': '#241319',
      'grey-200': '#2E1820',
      'grey-300': '#4B2A33',
      'grey-400': '#6D4650',
      'grey-500': '#947078',
      'grey-600': '#B89DA3',
      'grey-700': '#D0BEC2',
      'grey-800': '#E7DCE0',
      'grey-900': '#F8EFF2',
      'grey-light': '#2A171E',
      'perfect-scrollbar-thumb': '#4B2A33',
      'skin-bordered-background': '#1E1015',
      'skin-bordered-surface': '#1E1015',
    },
    variables: {
      'code-color': '#E2C15A',
      'overlay-scrim-background': '#070305',
      'tooltip-background': '#F7EFE7',
      'overlay-scrim-opacity': 0.6,
      'hover-opacity': 0.06,
      'focus-opacity': 0.1,
      'selected-opacity': 0.08,
      'activated-opacity': 0.16,
      'pressed-opacity': 0.14,
      'dragged-opacity': 0.1,
      'disabled-opacity': 0.4,
      'border-color': '#F6E9EC',
      'border-opacity': 0.12,
      'table-header-color': '#321B23',
      'high-emphasis-opacity': 0.9,
      'medium-emphasis-opacity': 0.7,
      'switch-opacity': 0.4,
      'switch-disabled-track-opacity': 0.4,
      'switch-disabled-thumb-opacity': 0.8,
      'switch-checked-disabled-opacity': 0.3,
      'track-bg': '#2A171E',

      // Shadows
      'shadow-key-umbra-color': '#070305',
      'shadow-xs-opacity': 0.16,
      'shadow-sm-opacity': 0.18,
      'shadow-md-opacity': 0.2,
      'shadow-lg-opacity': 0.22,
      'shadow-xl-opacity': 0.24,
    },
  },
}
export default themes
